Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.


In [22]:
import numpy as np
def power_matrix(vector,n,increasing=False):
     if not increasing:
        op_matx = np.array([x**(n-1-i) for x in vector for i in range(n)]).reshape(vector.size,n)
     elif increasing:
        op_matx = np.array([x**i for x in vector for i in range(n)]).reshape(vector.size,n)
    
     return op_matx


inputvector = np.array([1,2,3,4,5])
no_col_opmat = 3
op_matx_dec_order = power_matrix(inputvector,no_col_opmat,False)
op_matx_inc_order = power_matrix(inputvector,no_col_opmat,True)

print("The input array is:",inputvector,"\n")
print("Number of columns in output matrix should be:",no_col_opmat,"\n")
print("Vander matrix of the input array in decreasing order of powers:\n\n",op_matx_dec_order,"\n")
print("Vander matrix of the input array in increasing order of powers:\n\n",op_matx_inc_order,"\n")



The input array is: [1 2 3 4 5] 

Number of columns in output matrix should be: 3 

Vander matrix of the input array in decreasing order of powers:

 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]] 

Vander matrix of the input array in increasing order of powers:

 [[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]] 



Question: Write a function to find moving average in an array over a window:
 Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3

In [11]:
def avge(l,n):
    cumsum,avg_sums=[0],[]
    for i,x in enumerate(l,1):
        cumsum.append(cumsum[i-1] + x)
        if i>=n:
            avg_sum=round(((cumsum[i]-cumsum[i-n])/n),2)
            avg_sums.append(avg_sum)
    print('Moving average values list:' ,avg_sums)
    print('Length of list: ',len(avg_sums))
        

In [13]:
l= [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
n=3
avge(l,n)

Moving average values list: [5.0, 4.67, 5.67, 6.67, 9.67, 28.67, 49.33, 72.67, 84.0, 93.33, 116.33]
Length of list:  11
